project_id = "prisma-glow-15"

[api]
port = 56321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 57432
shadow_port = 57433
major_version = 15

[studio]
port = 55323

[inbucket]
port = 55324

[storage]
file_size_limit = 52428800

[auth]
site_url = "http://localhost:56321"
additional_redirect_urls = []
jwt_expiry = 3600

