import type { DomainAgentKey, DomainAgentMetadata } from './types';

export const DOMAIN_AGENTS: Record<DomainAgentKey, DomainAgentMetadata> = {
  auditExecution: {
    toolCatalog: ['rag.search', 'policy_check', 'audit.risk_summary'],
    datasetKeys: ['audit_risks', 'audit_responses'],
    knowledgeBases: ['ifrs', 'isa'],
    key: 'auditExecution',
    title: 'Audit Execution Agent',
    description:
      'Coordinates planning, risk assessment, analytics, sampling, KAM drafting, and evidence gathering aligned to ISA/ISQM.',
    status: 'in_progress',
    owner: 'Audit SME',
    capabilities: [
      'Materiality calculation',
      'Risk register maintenance',
      'Sampling & ADA execution',
      'KAM drafting',
      'Evidence ingestion',
    ],
    dependencies: ['knowledgeCurator', 'clientCollaboration', 'riskAndCompliance'],
    notes: 'Current implementation covers planning + limited tool calls; analytics and sampling automation pending.',
  },
  accountingClose: {
    toolCatalog: ['accounting.reconciliation_summary', 'accounting.journal_summary', 'accounting.close_summary', 'trial_balance.get'],
    datasetKeys: ['reconciliations', 'journal_entries', 'trial_balance'],
    knowledgeBases: ['close_checklists', 'ifrs'],
    key: 'accountingClose',
    title: 'Controller (CFO) Agent',
    description:
      'Oversees period close, cash flow, and management reporting. Coordinates reconciliations, journals, and trial balance reviews for leadership.',
    status: 'in_progress',
    owner: 'Finance Controller',
    capabilities: [
      'Close calendar orchestration',
      'Reconciliation oversight',
      'Journal approvals',
      'Variance analysis & cash flow insight',
      'Management summary packages',
    ],
    dependencies: ['dataPreparation', 'opsMonitoring', 'riskAndCompliance'],
  },
  accountsPayable: {
    toolCatalog: ['accounting.reconciliation_summary', 'accounting.journal_summary', 'document.vision_ocr'],
    datasetKeys: ['ap_invoices', 'ap_payments'],
    knowledgeBases: ['procure_to_pay'],
    key: 'accountsPayable',
    title: 'Accounts Payable Agent',
    description: 'Automates invoice intake, coding, approvals, and payment scheduling with variance alerts.',
    status: 'planned',
    owner: 'AP Lead',
    capabilities: [
      'Invoice OCR and coding',
      'Three-way matching',
      'Payment scheduling',
      'Aging and exception reporting',
    ],
    dependencies: ['dataPreparation', 'knowledgeCurator'],
    notes: 'Relies on document OCR and reconciliation summaries to surface exceptions.',
  },
  corporateFinance: {
    toolCatalog: ['rag.search', 'policy_check', 'document.vision_ocr', 'db.read'],
    datasetKeys: ['board_minutes', 'corporate_actions', 'treasury_positions'],
    knowledgeBases: ['corporate_policy', 'treasury_playbooks'],
    key: 'corporateFinance',
    title: 'Corporate Finance Agent',
    description: 'Supports treasury, board reporting, covenant monitoring, and strategic finance workflows.',
    status: 'planned',
    owner: 'Corporate Finance Lead',
    capabilities: [
      'Board/committee packs',
      'Covenant compliance tracking',
      'Treasury & liquidity monitoring',
      'Equity and debt action support',
    ],
    dependencies: ['accountingClose', 'riskAndCompliance'],
  },
  financialReporting: {
    toolCatalog: ['trial_balance.get', 'rag.search'],
    datasetKeys: ['trial_balance', 'financial_statements'],
    knowledgeBases: ['ifrs'],
    key: 'financialReporting',
    title: 'Financial Reporting Agent',
    description: 'Produces IFRS financials, note disclosures, XBRL packages, and management commentary.',
    status: 'planned',
    owner: 'Reporting SME',
    capabilities: ['Trial balance to statements', 'Note drafting', 'XBRL generation', 'Performance dashboards'],
    dependencies: ['accountingClose', 'knowledgeCurator'],
  },
  taxCompliance: {
    toolCatalog: ['rag.search', 'policy_check'],
    datasetKeys: ['tax_filings', 'transfer_pricing'],
    knowledgeBases: ['tax_guidance'],
    key: 'taxCompliance',
    title: 'Tax Compliance Agent',
    description: 'Executes CIT, VAT, transfer pricing, and cross-border workflows with jurisdictional policy checks.',
    status: 'in_progress',
    owner: 'Tax SME',
    capabilities: ['CIT computation', 'VAT filings', 'ATAD/TP reviews', 'Cross-border risk scoring'],
    dependencies: ['knowledgeCurator', 'riskAndCompliance'],
    notes: 'Current persona provides advisory responses; computation and filing orchestration pending.',
  },
  advisory: {
    toolCatalog: ['rag.search'],
    datasetKeys: ['valuation_models'],
    knowledgeBases: ['advisory_playbooks'],
    key: 'advisory',
    title: 'Advisory Agent',
    description: 'Supports transaction services, valuations, business plans, and KPI simulation.',
    status: 'planned',
    owner: 'Advisory SME',
    capabilities: ['Valuation models', 'Scenario analysis', 'Due diligence checklists'],
    dependencies: ['dataPreparation', 'knowledgeCurator'],
  },
  governance: {
    toolCatalog: ['policy_check'],
    datasetKeys: ['governance_policies'],
    knowledgeBases: ['soc_controls'],
    key: 'governance',
    title: 'Governance & Independence Agent',
    description: 'Monitors independence, SOC obligations, board governance, and policy compliance.',
    status: 'in_progress',
    owner: 'Risk SME',
    capabilities: ['Independence checks', 'SOC monitoring', 'Policy attestations', 'Autonomy gating'],
    dependencies: ['riskAndCompliance'],
  },
  clientCollaboration: {
    toolCatalog: ['notify.user'],
    datasetKeys: ['client_portal_messages'],
    knowledgeBases: ['engagement_guides'],
    key: 'clientCollaboration',
    title: 'Client Collaboration Agent',
    description: 'Manages portal messaging, deliverable distribution, and feedback loops.',
    status: 'planned',
    owner: 'Engagement Lead',
    capabilities: ['Portal messaging', 'Deliverable packaging', 'Feedback triage'],
    dependencies: ['opsMonitoring'],
  },
  dataPreparation: {
    toolCatalog: ['db.read'],
    datasetKeys: ['source_ingestion_jobs'],
    knowledgeBases: ['data_connectors'],
    key: 'dataPreparation',
    title: 'Data Preparation Agent',
    description: 'Handles ERP connectors, bank feeds, document OCR, and dataset normalization.',
    status: 'planned',
    owner: 'Data Engineering',
    capabilities: ['ERP ingestion', 'Bank feed matching', 'Document OCR', 'Dataset health checks'],
  },
  knowledgeCurator: {
    toolCatalog: ['rag.search'],
    datasetKeys: ['knowledge_sources'],
    knowledgeBases: ['taxonomy'],
    key: 'knowledgeCurator',
    title: 'Knowledge Curator Agent',
    description: 'Curates knowledge bases, classifications, embeddings, and refresh cadence.',
    status: 'in_progress',
    owner: 'Knowledge Ops',
    capabilities: ['Web harvesting', 'Document tagging', 'Embedding generation', 'Freshness alerts'],
    notes: 'web.harvest and embeddings exist; taxonomy and freshness scoring pending.',
  },
  riskAndCompliance: {
    toolCatalog: ['policy_check'],
    datasetKeys: ['risk_register'],
    knowledgeBases: ['compliance_guides'],
    key: 'riskAndCompliance',
    title: 'Risk & Compliance Agent',
    description: 'Automates policy checks, autonomy scoring, regulatory watchlists, and approvals.',
    status: 'in_progress',
    owner: 'Risk SME',
    capabilities: ['Policy engine', 'Autonomy scoring', 'Regulatory alerts', 'Audit trail generation'],
  },
  opsMonitoring: {
    toolCatalog: ['db.read'],
    datasetKeys: ['usage_metrics'],
    knowledgeBases: ['ops_runbooks'],
    key: 'opsMonitoring',
    title: 'Ops & Observability Agent',
    description: 'Tracks usage, cost, rate limits, alerting, and orchestrator health.',
    status: 'planned',
    owner: 'Platform Ops',
    capabilities: ['Cost dashboards', 'Rate limit alerts', 'Agent telemetry summarisation'],
  },
};

export const DOMAIN_AGENT_LIST = Object.values(DOMAIN_AGENTS);
