version: "3.9"

services:
  admin:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: admin-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    working_dir: /app
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 15s
      timeout: 3s
      retries: 20
    networks: [web]

  caddy:
    image: caddy:2
    container_name: admin-caddy
    restart: unless-stopped
    volumes:
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "8080:8080"
    depends_on:
      - admin
    networks: [web]

networks:
  web:
    driver: bridge
