version: '3.9'
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
  sentry:
    image: getsentry/sentry:latest
    depends_on:
      - postgres
      - redis
    environment:
      SENTRY_SECRET_KEY: devsecret
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_DB_HOST: postgres
      SENTRY_REDIS_HOST: redis
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    image: ${YOUR_DOCKER_REGISTRY:-local}/gateway:dev
    depends_on:
      - postgres
      - redis
  rag:
    build:
      context: .
      dockerfile: rag/Dockerfile
    image: ${YOUR_DOCKER_REGISTRY:-local}/rag:dev
    depends_on:
      - postgres
      - redis
  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    image: ${YOUR_DOCKER_REGISTRY:-local}/agent:dev
    depends_on:
      - postgres
      - redis
  analytics:
    build:
      context: .
      dockerfile: analytics/Dockerfile
    image: ${YOUR_DOCKER_REGISTRY:-local}/analytics:dev
    depends_on:
      - postgres
      - redis
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    image: ${YOUR_DOCKER_REGISTRY:-local}/ui:dev
    depends_on:
      - gateway
    ports:
      - "3000:3000"
volumes:
  postgres-data:
