version: '3.9'
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  sentry:
    image: getsentry/sentry:latest
    depends_on:
      - postgres
      - redis
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_DB_HOST: ${SENTRY_DB_HOST}
      SENTRY_REDIS_HOST: ${SENTRY_REDIS_HOST}
  gateway:
    image: ${GATEWAY_IMAGE}
    depends_on:
      - postgres
      - redis
  rag:
    image: ${RAG_IMAGE}
    depends_on:
      - postgres
      - redis
  agent:
    image: ${AGENT_IMAGE}
    depends_on:
      - postgres
      - redis
  analytics:
    image: ${ANALYTICS_IMAGE}
    depends_on:
      - postgres
      - redis
  ui:
    image: ${UI_IMAGE}
    depends_on:
      - gateway
    ports:
      - "3000:3000"
volumes:
  postgres-data:
