# pnpm Workspace Configuration for easyMO Refactor
packages:
  - "packages/*"
  - "packages/lib-core"
  - "packages/types"
  - "packages/edge-functions"
  - "packages/testing"
  - "packages/openai-sdk"
  - "packages/wa-utils"
  - "apps/*"
  - "apps/wa-router"
  - "supabase/functions/*"
