import type { DomainAgentKey, DomainAgentMetadata } from './types.js';

export const DOMAIN_AGENTS: Record<DomainAgentKey, DomainAgentMetadata> = {
  auditExecution: {
    toolCatalog: ['rag.search', 'policy_check', 'audit.risk_summary'],
    datasetKeys: ['audit_risks', 'audit_responses'],
    knowledgeBases: ['ifrs', 'isa'],
    key: 'auditExecution',
    title: 'Audit Execution Agent',
    description:
      'Coordinates planning, risk assessment, analytics, sampling, KAM drafting, and evidence gathering aligned to ISA/ISQM.',
    status: 'in_progress',
    owner: 'Audit SME',
    capabilities: [
      'Materiality calculation',
      'Risk register maintenance',
      'Sampling & ADA execution',
      'KAM drafting',
      'Evidence ingestion',
    ],
    dependencies: ['knowledgeCurator', 'clientCollaboration', 'riskAndCompliance'],
    notes: 'Current implementation covers planning + limited tool calls; analytics and sampling automation pending.',
  },
  accountingClose: {
    toolCatalog: ['accounting.reconciliation_summary', 'accounting.journal_summary', 'accounting.close_summary', 'trial_balance.get'],
    datasetKeys: ['reconciliations', 'journal_entries', 'trial_balance'],
    knowledgeBases: ['close_checklists', 'ifrs'],
    key: 'accountingClose',
    title: 'Controller (CFO) Agent',
    description:
      'Oversees period close, cash flow, and management reporting. Coordinates reconciliations, journals, and trial balance reviews for leadership.',
    status: 'in_progress',
    owner: 'Finance Controller',
    capabilities: [
      'Close calendar orchestration',
      'Reconciliation oversight',
      'Journal approvals',
      'Variance analysis & cash flow insight',
      'Management summary packages',
    ],
    dependencies: ['dataPreparation', 'opsMonitoring', 'riskAndCompliance'],
  },
  accountsPayable: {
    toolCatalog: ['accounting.reconciliation_summary', 'accounting.journal_summary', 'document.vision_ocr'],
    datasetKeys: ['ap_invoices', 'ap_payments'],
    knowledgeBases: ['procure_to_pay'],
    key: 'accountsPayable',
    title: 'Accounts Payable Agent',
    description: 'Automates invoice intake, coding, approvals, and payment scheduling with variance alerts.',
    status: 'planned',
    owner: 'AP Lead',
    capabilities: [
      'Invoice OCR and coding',
      'Three-way matching',
      'Payment scheduling',
      'Aging and exception reporting',
    ],
    dependencies: ['dataPreparation', 'knowledgeCurator'],
    notes: 'Relies on document OCR and reconciliation summaries to surface exceptions.',
  },
  corporateFinance: {
    toolCatalog: ['rag.search', 'policy_check', 'document.vision_ocr', 'db.read'],
    datasetKeys: ['board_minutes', 'corporate_actions', 'treasury_positions'],
    knowledgeBases: ['corporate_policy', 'treasury_playbooks'],
    key: 'corporateFinance',
    title: 'Corporate Finance Agent',
    description: 'Supports treasury, board reporting, covenant monitoring, and strategic finance workflows.',
    status: 'planned',
    owner: 'Corporate Finance Lead',
    capabilities: [
      'Board/committee packs',
      'Covenant compliance tracking',
      'Treasury & liquidity monitoring',
      'Equity and debt action support',
    ],
    dependencies: ['accountingClose', 'riskAndCompliance'],
  },
  brokerageEnablement: {
    toolCatalog: [
      'openai.web_search',
      'openai.file_search',
      'openai.vector_search',
      'openai.image_generation',
      'openai.gpt5_responses',
    ],
    datasetKeys: ['broker_pipeline', 'deal_rooms', 'market_intelligence'],
    knowledgeBases: ['capital_markets_playbooks', 'product_catalogues'],
    key: 'brokerageEnablement',
    title: 'Broker AI Agent',
    description:
      'Synthesises market intelligence, prepares collateral, and coordinates digital brokerage workflows across channels.',
    status: 'in_progress',
    owner: 'Brokerage Ops Lead',
    capabilities: [
      'Real-time market briefings with sourced citations',
      'Prospect dossier assembly from first- and third-party data',
      'Sales collateral and pitch automation (copy + imagery)',
      'Compliance-aware outreach sequencing',
      'Deal room knowledge upkeep leveraging vector stores',
    ],
    dependencies: ['corporateFinance', 'knowledgeCurator', 'riskAndCompliance'],
    tooling: [
      {
        name: 'Web Search Intelligence',
        summary:
          'Uses the Responses API web_search tool to aggregate the latest market movements with inline citations and optional domain filters.',
        apis: ['responses.create', 'web_search tool'],
        notes: 'Supports user location hints and full source lists for broker compliance packs.',
      },
      {
        name: 'File + Vector Retrieval',
        summary:
          'Blends file_search tool calls with direct vector store semantic search to surface archived deal collateral and research.',
        apis: ['responses.create', 'file_search tool', 'vector_stores.search'],
        notes: 'Respects metadata filters such as product line and jurisdiction.',
      },
      {
        name: 'Image Generation',
        summary:
          'Generates on-brand imagery for decks and listings through the image_generation tool with prompt revision support.',
        apis: ['responses.create', 'image_generation tool'],
      },
      {
        name: 'GPT-5 Reasoning',
        summary:
          'Runs GPT-5 with configurable reasoning effort and verbosity to draft broker memos and scenario analyses.',
        apis: ['responses.create (gpt-5)'],
      },
    ],
    notes: 'Requires OPENAI_WEB_SEARCH_ENABLED and configured vector stores to access live market data.',
  },
  financialReporting: {
    toolCatalog: ['trial_balance.get', 'rag.search'],
    datasetKeys: ['trial_balance', 'financial_statements'],
    knowledgeBases: ['ifrs'],
    key: 'financialReporting',
    title: 'Financial Reporting Agent',
    description: 'Produces IFRS financials, note disclosures, XBRL packages, and management commentary.',
    status: 'planned',
    owner: 'Reporting SME',
    capabilities: ['Trial balance to statements', 'Note drafting', 'XBRL generation', 'Performance dashboards'],
    dependencies: ['accountingClose', 'knowledgeCurator'],
  },
  taxCompliance: {
    toolCatalog: ['rag.search', 'policy_check'],
    datasetKeys: ['tax_filings', 'transfer_pricing'],
    knowledgeBases: ['tax_guidance'],
    key: 'taxCompliance',
    title: 'Tax Compliance Agent',
    description: 'Executes CIT, VAT, transfer pricing, and cross-border workflows with jurisdictional policy checks.',
    status: 'in_progress',
    owner: 'Tax SME',
    capabilities: ['CIT computation', 'VAT filings', 'ATAD/TP reviews', 'Cross-border risk scoring'],
    dependencies: ['knowledgeCurator', 'riskAndCompliance'],
    notes: 'Current persona provides advisory responses; computation and filing orchestration pending.',
  },
  advisory: {
    toolCatalog: ['rag.search'],
    datasetKeys: ['valuation_models'],
    knowledgeBases: ['advisory_playbooks'],
    key: 'advisory',
    title: 'Advisory Agent',
    description: 'Supports transaction services, valuations, business plans, and KPI simulation.',
    status: 'planned',
    owner: 'Advisory SME',
    capabilities: ['Valuation models', 'Scenario analysis', 'Due diligence checklists'],
    dependencies: ['dataPreparation', 'knowledgeCurator'],
  },
  governance: {
    toolCatalog: ['policy_check'],
    datasetKeys: ['governance_policies'],
    knowledgeBases: ['soc_controls'],
    key: 'governance',
    title: 'Governance & Independence Agent',
    description: 'Monitors independence, SOC obligations, board governance, and policy compliance.',
    status: 'in_progress',
    owner: 'Risk SME',
    capabilities: ['Independence checks', 'SOC monitoring', 'Policy attestations', 'Autonomy gating'],
    dependencies: ['riskAndCompliance'],
  },
  clientCollaboration: {
    toolCatalog: ['notify.user'],
    datasetKeys: ['client_portal_messages'],
    knowledgeBases: ['engagement_guides'],
    key: 'clientCollaboration',
    title: 'Client Collaboration Agent',
    description: 'Manages portal messaging, deliverable distribution, and feedback loops.',
    status: 'planned',
    owner: 'Engagement Lead',
    capabilities: ['Portal messaging', 'Deliverable packaging', 'Feedback triage'],
    dependencies: ['opsMonitoring'],
  },
  dataPreparation: {
    toolCatalog: ['db.read'],
    datasetKeys: ['source_ingestion_jobs'],
    knowledgeBases: ['data_connectors'],
    key: 'dataPreparation',
    title: 'Data Preparation Agent',
    description: 'Handles ERP connectors, bank feeds, document OCR, and dataset normalization.',
    status: 'planned',
    owner: 'Data Engineering',
    capabilities: ['ERP ingestion', 'Bank feed matching', 'Document OCR', 'Dataset health checks'],
  },
  knowledgeCurator: {
    toolCatalog: ['rag.search'],
    datasetKeys: ['knowledge_sources'],
    knowledgeBases: ['taxonomy'],
    key: 'knowledgeCurator',
    title: 'Knowledge Curator Agent',
    description: 'Curates knowledge bases, classifications, embeddings, and refresh cadence.',
    status: 'in_progress',
    owner: 'Knowledge Ops',
    capabilities: ['Web harvesting', 'Document tagging', 'Embedding generation', 'Freshness alerts'],
    notes: 'web.harvest and embeddings exist; taxonomy and freshness scoring pending.',
  },
  riskAndCompliance: {
    toolCatalog: ['policy_check'],
    datasetKeys: ['risk_register'],
    knowledgeBases: ['compliance_guides'],
    key: 'riskAndCompliance',
    title: 'Risk & Compliance Agent',
    description: 'Automates policy checks, autonomy scoring, regulatory watchlists, and approvals.',
    status: 'in_progress',
    owner: 'Risk SME',
    capabilities: ['Policy engine', 'Autonomy scoring', 'Regulatory alerts', 'Audit trail generation'],
  },
  opsMonitoring: {
    toolCatalog: ['db.read'],
    datasetKeys: ['usage_metrics'],
    knowledgeBases: ['ops_runbooks'],
    key: 'opsMonitoring',
    title: 'Ops & Observability Agent',
    description: 'Tracks usage, cost, rate limits, alerting, and orchestrator health.',
    status: 'planned',
    owner: 'Platform Ops',
    capabilities: ['Cost dashboards', 'Rate limit alerts', 'Agent telemetry summarisation'],
  },
  callerMarketing: {
    toolCatalog: [
      'openai.web_search',
      'openai.file_search',
      'openai.vector_search',
      'openai.image_generation',
      'openai.gpt5_responses',
    ],
    datasetKeys: ['call_scripts', 'campaign_performance', 'crm_notes'],
    knowledgeBases: ['marketing_playbooks', 'brand_guidelines'],
    key: 'callerMarketing',
    title: 'Caller Marketing Agent',
    description:
      'Coordinates outbound call campaigns, personalises scripts, and monitors engagement telemetry for marketing teams.',
    status: 'in_progress',
    owner: 'Growth Marketing Lead',
    capabilities: [
      'Dynamic call script authoring with GPT-5 reasoning',
      'Audience research via real-time web and file search',
      'Campaign insight boards from vector store retrieval',
      'Creative asset refreshes via image generation',
      'Compliance guardrails with citation-tracked messaging',
    ],
    dependencies: ['clientCollaboration', 'knowledgeCurator', 'opsMonitoring'],
    tooling: [
      {
        name: 'Audience Web Search',
        summary:
          'Executes agentic web lookups before dial sessions, enriching lead dossiers with citations and geography-aware context.',
        apis: ['responses.create', 'web_search tool'],
      },
      {
        name: 'Knowledge File Search',
        summary: 'Leverages marketing collateral vector stores for script snippets and objection handling references.',
        apis: ['responses.create', 'file_search tool'],
      },
      {
        name: 'Vector Store Insights',
        summary: 'Runs semantic retrieval with rewrite support to collate campaign performance highlights.',
        apis: ['vector_stores.search'],
      },
      {
        name: 'Creative Refresh',
        summary: 'Generates updated hero images for nurture sequences with tunable size and quality.',
        apis: ['responses.create', 'image_generation tool'],
      },
    ],
    notes: 'Optimised for omni-channel calling pods that require rapid research and asset refreshes.',
  },
  mobilityOps: {
    toolCatalog: [
      'openai.web_search',
      'openai.file_search',
      'openai.vector_search',
      'openai.image_generation',
      'openai.gpt5_responses',
    ],
    datasetKeys: ['fleet_status', 'route_guides', 'service_bulletins'],
    knowledgeBases: ['mobility_policies', 'safety_manuals'],
    key: 'mobilityOps',
    title: 'Mobility Operations Agent',
    description:
      'Supports transport networks with service alerts, fleet intelligence, and rider comms built on live and indexed data.',
    status: 'planned',
    owner: 'Mobility COO',
    capabilities: [
      'Incident-aware rider briefings with GPT-5 reasoning',
      'Local regulation scanning via web search',
      'Maintenance bulletin retrieval from vector stores',
      'Route signage and announcement visuals through image generation',
      'Structured report drafting with citations for regulators',
    ],
    dependencies: ['opsMonitoring', 'riskAndCompliance', 'dataPreparation'],
    tooling: [
      {
        name: 'Regulation Web Search',
        summary:
          'Queries current mobility advisories and city notices with optional domain allow lists for trusted transport authorities.',
        apis: ['responses.create', 'web_search tool'],
      },
      {
        name: 'Maintenance File Search',
        summary: 'Finds latest service bulletins and SOPs stored in vectorised knowledge hubs.',
        apis: ['responses.create', 'file_search tool'],
      },
      {
        name: 'Semantic Fleet Retrieval',
        summary:
          'Surfaces historical incidents and telemetry using vector store semantic search with attribute filters (vehicle type, depot).',
        apis: ['vector_stores.search'],
      },
      {
        name: 'Visual Alert Generation',
        summary: 'Produces platform-ready signage and rider notices using image generation presets.',
        apis: ['responses.create', 'image_generation tool'],
      },
      {
        name: 'GPT-5 Briefings',
        summary: 'Generates structured status briefings leveraging GPT-5 reasoning and verbosity controls.',
        apis: ['responses.create (gpt-5)'],
      },
    ],
    notes: 'Integrates with fleet telematics vector stores for contextual retrieval.',
  },
};

export const DOMAIN_AGENT_LIST = Object.values(DOMAIN_AGENTS);
