export const JE_CONTROL_SEVERITIES: Record<string, 'LOW' | 'MEDIUM' | 'HIGH'> = {
  LATE_POSTING: 'HIGH',
  WEEKEND_USER: 'MEDIUM',
  ROUND_AMOUNT: 'MEDIUM',
  MANUAL_TO_SENSITIVE: 'HIGH',
  MISSING_ATTACHMENT: 'LOW',
};

export const SENSITIVE_ACCOUNT_TYPES = new Set(['ASSET', 'LIABILITY', 'EQUITY']);
export const ROUND_AMOUNT_STEP = 1000;
export const MAX_JE_IMBALANCE = 0.005;
