blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/ikanisa/prisma/tree/main/docs
    about: Check our comprehensive documentation before opening an issue
  - name: 💬 GitHub Discussions
    url: https://github.com/ikanisa/prisma/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/ikanisa/prisma/security/advisories/new
    about: Report security vulnerabilities privately
