/**
 * Journal Entry Types
 * 
 * Type definitions for journal entries and transactions.
 */

// ============================================================================
// JOURNAL ENTRY TYPES
// ============================================================================

/**
 * Transaction types for journal entries.
 */
export type TransactionType =
    | 'JOURNAL'           // Manual journal entry
    | 'INVOICE'           // Sales/purchase invoice
    | 'PAYMENT'           // Payment transaction
    | 'RECEIPT'           // Receipt transaction
    | 'BANK_TRANSACTION'  // Bank statement transaction
    | 'ADJUSTING'         // Adjusting entry (accruals, prepayments)
    | 'CLOSING'           // Year-end closing entry
    | 'REVERSING'         // Reversing entry
    | 'DEPRECIATION'      // Depreciation entry
    | 'REVALUATION';      // Revaluation entry

/**
 * Single line in a journal entry (debit or credit).
 */
export interface JournalEntryLine {
    /** Account number */
    account: string;
    /** Account name (for display) */
    accountName?: string;
    /** Amount (always positive) */
    amount: number;
    /** Description for this line */
    description: string;
    /** GAPSME classification for reporting */
    gapsmeClassification?: string;
    /** IFRS standard reference */
    ifrsStandard?: string;
}

/**
 * Complete journal entry with debit and credit sides.
 */
export interface JournalEntry {
    /** Unique identifier */
    id?: string;
    /** Company ID */
    companyId: string;
    /** Transaction date */
    date: Date;
    /** Debit side of entry */
    debit: JournalEntryLine;
    /** Credit side of entry */
    credit: JournalEntryLine;
    /** Reference number */
    reference: string;
    /** Transaction narrative/description */
    narrative: string;
    /** Transaction type */
    type: TransactionType;
    /** Whether entry was AI-generated */
    automated: boolean;
    /** Whether entry was generated by AI agent */
    aiGenerated: boolean;
    /** AI confidence score (0-1) */
    confidenceScore?: number;
    /** Whether human review is required */
    reviewRequired: boolean;
    /** Review status */
    reviewStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';
    /** Reviewer notes */
    reviewNotes?: string;
    /** Created by user ID */
    createdBy?: string;
    /** Approved by user ID */
    approvedBy?: string;
    /** Approval timestamp */
    approvedAt?: Date;
    /** Created timestamp */
    createdAt?: Date;
    /** Updated timestamp */
    updatedAt?: Date;
}

/**
 * Multi-line journal entry for complex transactions.
 */
export interface MultiLineJournalEntry {
    /** Unique identifier */
    id?: string;
    /** Company ID */
    companyId: string;
    /** Transaction date */
    date: Date;
    /** Debit lines (total must equal credit total) */
    debits: JournalEntryLine[];
    /** Credit lines (total must equal debit total) */
    credits: JournalEntryLine[];
    /** Reference number */
    reference: string;
    /** Transaction narrative/description */
    narrative: string;
    /** Transaction type */
    type: TransactionType;
    /** Whether entry was AI-generated */
    aiGenerated: boolean;
    /** AI confidence score (0-1) */
    confidenceScore?: number;
    /** Whether human review is required */
    reviewRequired: boolean;
}

/**
 * Raw transaction input for AI processing.
 */
export interface RawTransaction {
    /** Transaction description (natural language) */
    description: string;
    /** Transaction amount */
    amount: number;
    /** Transaction date */
    date: Date;
    /** Currency (default EUR) */
    currency?: string;
    /** Accounting framework for entry generation */
    framework: 'GAPSME' | 'IFRS';
    /** Source of transaction */
    source?: string;
    /** Additional metadata */
    metadata?: Record<string, unknown>;
}

/**
 * Journal entry validation result.
 */
export interface JournalEntryValidation {
    valid: boolean;
    errors: string[];
    warnings: string[];
}

// ============================================================================
// TRIAL BALANCE
// ============================================================================

/**
 * Trial balance entry for a single account.
 */
export interface TrialBalanceEntry {
    accountNumber: string;
    accountName: string;
    accountType: string;
    category: string;
    debitBalance: number;
    creditBalance: number;
    netBalance: number;
}

/**
 * Complete trial balance.
 */
export interface TrialBalance {
    companyId: string;
    companyName: string;
    asAt: Date;
    entries: TrialBalanceEntry[];
    totalDebits: number;
    totalCredits: number;
    isBalanced: boolean;
}
