controllerManager:
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  serviceAccount:
    name: chaos-controller-manager
    create: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

dashboard:
  create: true
  service:
    type: ClusterIP
  securityMode: false
  persistentVolume:
    enabled: true
    size: 5Gi

prometheus:
  create: false
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

chaosDaemon:
  runtime: containerd
  socketPath: /run/containerd/containerd.sock
