meta:
  name: "Autonomous Finance Suite"
  version: "1.0.0"

principles:
  - "AI-first, document-first, zero typing"
  - "Deterministic math; LLMs for reasoning/drafting"
  - "Citations and provenance required"
  - "HITL approvals for filings/lock/report"

autonomy:
  levels:
    L0: "Manual: user triggers everything"
    L1: "Suggest: agent proposes actions; user approves"
    L2: "Auto-prepare: agent drafts & stages; user approves to submit/file"
    L3: "Autopilot: agent executes within policy; asks only if evidence is missing"
  default_level: "L2"
  autopilot:
    allowed_jobs:
      L0: []
      L1:
        - "refresh_analytics"
      L2:
        - "extract_documents"
        - "remind_pbc"
        - "refresh_analytics"
        - "close_cycle"
        - "audit_fieldwork"
        - "tax_cycle"
      L3:
        - "extract_documents"
        - "remind_pbc"
        - "refresh_analytics"
        - "close_cycle"
        - "audit_fieldwork"
        - "tax_cycle"

rbac:
  roles:
    - SYSTEM_ADMIN
    - PARTNER
    - MANAGER
    - EMPLOYEE
    - CLIENT
    - READONLY
    - SERVICE_ACCOUNT
    - EQR
  matrix:
    close.lock: PARTNER
    journal.post: MANAGER
    audit.plan.freeze: PARTNER
    audit.report.release: PARTNER
    eqr.signoff: EQR
    tax.return.submit: MANAGER
    client.portal.view: CLIENT
  permissions:
    tasks.create: EMPLOYEE
    tasks.update: EMPLOYEE
    tasks.assign: MANAGER
    documents.upload: EMPLOYEE
    documents.view_internal: EMPLOYEE
    documents.view_client: CLIENT
    onboarding.start: EMPLOYEE
    onboarding.commit: MANAGER
    journals.post: MANAGER
    close.lock: PARTNER
    audit.plan.freeze: PARTNER
    audit.report.release: PARTNER
    audit.eqr.signoff: EQR
    tax.return.submit: MANAGER
    policy.pack.edit: SYSTEM_ADMIN
  client_scope: &client_scope
    allowed_repos:
      - "02_Tax/PBC"
      - "03_Accounting/PBC"
      - "05_Payroll/PBC"
  client_portal_scope:
    <<: *client_scope
    denied_actions:
      - "documents.view_internal"
      - "close.lock"
      - "audit.plan.freeze"
      - "audit.report.release"

datasources: &modern_datasources
  supabase_url: "${SUPABASE_URL}"
  vector_index: "pgvector_finance_docs"
  google_drive:
    enabled: true
    mirror_to_storage: true
  url_sources:
    whitelist:
      - "*"
    policy:
      obey_robots: true
      max_depth: 1
      cache_ttl_minutes: 1440
  document_repos:
    - "01_Legal"
    - "02_Tax"
    - "03_Accounting"
    - "04_Banking"
    - "05_Payroll"
    - "06_Contracts"
    - "07_Audit"
    - "99_Other"
  email_ingest:
    enabled: false

encryption:
  supabase:
    provider: "${SUPABASE_ENCRYPTION_PROVIDER:-aws}"
    key_reference: "${SUPABASE_ENCRYPTION_KEY_REFERENCE}"
    rotation_days: 90
  object_storage:
    provider: "${OBJECT_STORAGE_ENCRYPTION_PROVIDER:-aws}"
    key_reference: "${OBJECT_STORAGE_ENCRYPTION_KEY_REFERENCE}"
    rotation_days: 90
  job_queue:
    provider: "${JOB_QUEUE_ENCRYPTION_PROVIDER:-aws}"
    key_reference: "${JOB_QUEUE_ENCRYPTION_KEY_REFERENCE}"
    rotation_days: 90

data_sources:
  supabase:
    project_url: "${SUPABASE_URL}"
    anon_key_ref: "SUPABASE_ANON_KEY"
    rls: true
  google_drive:
    enabled: true
    oauth_required_scopes:
      - "https://www.googleapis.com/auth/drive.readonly"
      - "https://www.googleapis.com/auth/drive.metadata.readonly"
    folder_mapping_pattern: "org-{orgId}/entity-{entityId}/{repoFolder}"
    mirror_to_storage: true
  url_sources:
    allowed_domains:
      - "*"
    fetch_policy:
      obey_robots: true
      max_depth: 1
      cache_ttl_minutes: 1440
  email_ingest:
    enabled: false

repositories:
  folders:
    - "01_Legal"
    - "02_Tax"
    - "03_Accounting"
    - "04_Banking"
    - "05_Payroll"
    - "06_Contracts"
    - "07_Audit"
    - "99_Other"
  pbc_subfolders:
    - "02_Tax/PBC"
    - "03_Accounting/PBC"
    - "05_Payroll/PBC"

rag:
  embedding_model: "text-embedding-3-large"
  chunk_size: 1200
  overlap: 150
  filters:
    - "orgId"
    - "entityId"
    - "repoFolder"
    - "docType"
  top_k: 8
  reranker: "mini-lm-re-ranker-v2"
  min_citation_confidence: 0.60
  before_asking_user:
    - "documents"
    - "google_drive"
    - "url_sources"

knowledge:
  vector_indexes:
    - name: "finance_docs_v1"
      backend: "pgvector"
      embedding_model: "text-embedding-3-large"
      scope_filters:
        - "orgId"
        - "entityId"
        - "repoFolder"
        - "docType"
      chunking:
        size: 1200
        overlap: 150
      seed_sets:
        - "IFRS/IAS primary texts"
        - "ISAs/ISQM/IESBA excerpts (permitted excerpts; do not store full proprietary texts)"
        - "EU directives & ESEF manual (public)"
        - "Malta GAPSME (public summaries)"
        - "Local regulator FAQs (public)"
  retrieval:
    reranker: "mini-lm-re-ranker-v2"
    top_k: 8
    min_citation_confidence: 0.60
    policy:
      before_asking_user:
        - "documents"
        - "google_drive"
        - "url_sources"
      require_citation: true

openai:
  agents_sdk: true
  responses_api: true
  chat_completions: true
  realtime_voice: true
  web_search: true
  api_base: "${OPENAI_BASE_URL}"
  key_ref: "OPENAI_API_KEY"

assistant:
  refusal_rules:
    - "Do not fabricate. If required evidence is missing, enumerate specific missing docs and where they would be found."
    - "For numbers, use calculators; never infer from narrative."
  citation_required: true
  ask_user_last: true

assistant_policies:
  style_rules:
    - "Every assistant response must conclude with the next two suggested actions for the user."
    - "Explain briefly why the recommendation is being made; keep the summary under 480 characters."

ui:
  shell:
    assistant_dock: true
    assistant_position: "bottom-right"
    style:
      theme: "modern-gradient"
      motion: "subtle"
      pwa_enabled: true
      mobile_first: true
    entry_points:
      - page: "Dashboard"
        chips:
          - "Add company"
          - "What’s next?"
          - "Upload PBC"
          - "Explain this page"
      - page: "Onboarding"
        chips:
          - "Show required docs"
          - "Scan uploaded files"
          - "Accept extracted data"
          - "Commit entity"
      - page: "Documents"
        chips:
          - "Summarize document"
          - "Extract key fields"
          - "Find similar"
          - "Link to task"
      - page: "Accounting Close"
        chips:
          - "Run bank rec"
          - "Propose JE"
          - "Explain variance"
          - "Lock period"
      - page: "Audit"
        chips:
          - "Create audit plan"
          - "Run sampling"
          - "Draft KAM"
          - "Assemble report"
      - page: "Tax"
        chips:
          - "Compute CIT"
          - "Build VAT return"
          - "Check DAC6"
          - "Pillar Two scope"
  dock:
    enabled: true
    hotkey: "⌘K"
    chips:
      - "Add company"
      - "Upload PBC"
      - "Explain this page"
      - "What’s next?"
    voice:
      enabled: true
      push_to_talk: true
  pages:
    - route: "/"
      name: "Dashboard"
    - route: "/onboarding"
      name: "Onboarding"
    - route: "/documents"
      name: "Documents"
    - route: "/tasks"
      name: "Tasks"
    - route: "/close"
      name: "Accounting Close"
    - route: "/audit"
      name: "Audit"
    - route: "/tax"
      name: "Tax"
    - route: "/admin"
      name: "Admin"
  empty_states:
    tasks: "No tasks yet — try 'Add onboarding checklist'."
    documents: "Drop files here. I’ll read them and extract what’s needed."
    notifications: "You’re all caught up."

workflows:
  enabled: true
  definitions:
    onboarding_zero_typing:
      trigger: "user:Add company"
      steps:
        - "onboarding.start"
        - "documents.upload_url"
        - "doc_ai.extract"
        - "onboarding.link_doc"
        - "onboarding.commit"
        - "tasks.create"
    monthly_close:
      steps:
        - "close.snapshot_tb"
        - "recon.bank"
        - "journals.propose"
        - "variance.analyze"
        - "cashflow.build_indirect"
      approval: "close.lock"
    audit_cycle:
      steps:
        - "audit.plan"
        - "sampling.design"
        - "confirmations.manage"
        - "estimates.evaluate"
        - "gc.assess"
        - "se.review"
        - "kam.draft"
        - "report.assemble"
        - "tcwg.pack"
      approvals:
        - "audit.plan.freeze"
        - "audit.report.release"
        - "eqr.signoff"
    tax_cycle:
      steps:
        - "mt.cit.compute"
        - "mt.vat.prepare"
        - "dac6.classify"
        - "p2.scope"
        - "p2.compute"
      approvals:
        - "tax.return.submit"

agents:
  - id: orchestrator
    autonomy: L2
    tools:
      - "documents.list"
      - "web_search"
      - "tasks.create"
      - "notifications.send"
  - id: onboarding_agent
    autonomy: L2
    tools:
      - "documents.list"
      - "documents.upload_url"
      - "doc_ai.extract"
      - "onboarding.start"
      - "onboarding.link_doc"
      - "onboarding.commit"
      - "tasks.create"
  - id: accountant_agent
    autonomy: L2
    tools:
      - "close.snapshot_tb"
      - "recon.bank"
      - "journals.propose"
      - "journals.post"
      - "variance.analyze"
      - "cashflow.build_indirect"
      - "documents.list"
      - "notifications.send"
    approvals:
      - "journals.post"
      - "close.lock"
  - id: audit_partner_agent
    autonomy: L1
    tools:
      - "audit.plan"
      - "sampling.design"
      - "confirmations.manage"
      - "estimates.evaluate"
      - "gc.assess"
      - "se.review"
      - "kam.draft"
      - "report.assemble"
      - "tcwg.pack"
    approvals:
      - "audit.plan.freeze"
      - "audit.report.release"
      - "eqr.signoff"
  - id: tax_partner_agent
    autonomy: L1
    tools:
      - "mt.cit.compute"
      - "mt.vat.prepare"
      - "dac6.classify"
      - "p2.scope"
      - "p2.compute"

pwa:
  manifest:
    name: "Autonomous Finance Suite"
    short_name: "AFS"
  sw_cache:
    strategy: "stale-while-revalidate"
    api_max_age: "60s"

telemetry:
  namespace: "prisma-glow"
  default_service: "backend-api"
  default_environment_env: "SENTRY_ENVIRONMENT"
  dashboards:
    - "assistant_adoption"
    - "doc_pipeline"
    - "compliance"
    - "security"
  disabled_environments:
    - "development"
    - "test"
    - "local"
  require_exporter: true
  exporters:
    traces:
      - name: "default"
        protocol: "otlp_http"
        endpoint_env: "OTEL_EXPORTER_OTLP_ENDPOINT"
        headers_env: "OTEL_EXPORTER_OTLP_HEADERS"

open_workflows:
  onboarding_zero_typing: true
