apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineering
  description: Core maintainers of the Prisma Glow platform.
  annotations:
    backstage.io/techdocs-ref: dir:../../docs
spec:
  type: organization
  profile:
    displayName: Platform Engineering
    email: platform@prismaglow.example
  children:
    - data-insights
    - conversation-intelligence
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: data-insights
  description: Owns the analytics ingestion and reporting pipelines.
spec:
  type: team
  parent: platform-engineering
  profile:
    displayName: Data Insights Team
    email: data-insights@prismaglow.example
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: conversation-intelligence
  description: Maintains conversational AI and retrieval augmented generation services.
spec:
  type: team
  parent: platform-engineering
  profile:
    displayName: Conversation Intelligence Team
    email: conversation-intelligence@prismaglow.example
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: prisma-ai-platform
  description: Core platform that powers analytics, retrieval and agent experiences across Prisma Glow.
  tags:
    - ai
    - platform
    - prisma-glow
spec:
  owner: group:platform-engineering
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-service
  description: |
    FastAPI application that ingests structured telemetry, applies validation and enrichment, and
    publishes normalised analytics events for the rest of the platform.
  tags:
    - python
    - fastapi
    - telemetry
  annotations:
    prisma.io/service-path: services/analytics
    backstage.io/source-location: url:https://github.com/prisma/prisma/tree/main/services/analytics
spec:
  type: service
  lifecycle: production
  owner: group:data-insights
  system: prisma-ai-platform
  providesApis:
    - analytics-events
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: analytics-events
  description: REST interface for submitting analytics events and instrumentation payloads.
  tags:
    - rest
    - ingestion
spec:
  type: openapi
  lifecycle: production
  owner: group:data-insights
  system: prisma-ai-platform
  definition: |
    openapi: 3.0.0
    info:
      title: Analytics Events API
      version: 1.0.0
    paths: {}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rag-service
  description: |
    TypeScript service that orchestrates retrieval augmented generation, handles OpenAI interactions,
    and exposes multi-channel agent experiences including audio and streaming responses.
  tags:
    - node
    - typescript
    - rag
  annotations:
    prisma.io/service-path: services/rag
    backstage.io/source-location: url:https://github.com/prisma/prisma/tree/main/services/rag
spec:
  type: service
  lifecycle: production
  owner: group:conversation-intelligence
  system: prisma-ai-platform
  providesApis:
    - rag-session-api
  dependsOn:
    - component:analytics-service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rag-session-api
  description: Interfaces for conversational retrieval sessions, streaming completions and agent control.
  tags:
    - websocket
    - rest
    - openai
spec:
  type: openapi
  lifecycle: production
  owner: group:conversation-intelligence
  system: prisma-ai-platform
  definition: |
    openapi: 3.0.0
    info:
      title: RAG Session API
      version: 1.0.0
    paths: {}
