export const Constants = {
    graphql_public: {
        Enums: {},
    },
    public: {
        Enums: {
            agent_action_status: ["PENDING", "SUCCESS", "ERROR", "BLOCKED"],
            agent_orchestration_status: [
                "PENDING",
                "RUNNING",
                "WAITING_APPROVAL",
                "COMPLETED",
                "FAILED",
            ],
            agent_run_state: ["PLANNING", "EXECUTING", "DONE", "ERROR"],
            agent_task_status: [
                "PENDING",
                "ASSIGNED",
                "IN_PROGRESS",
                "AWAITING_APPROVAL",
                "COMPLETED",
                "FAILED",
            ],
            agent_trace_type: ["INFO", "TOOL", "ERROR"],
            audit_risk_category: [
                "FINANCIAL_STATEMENT",
                "FRAUD",
                "CONTROL",
                "IT",
                "GOING_CONCERN",
                "COMPLIANCE",
                "ESTIMATE",
                "OTHER",
            ],
            cit_refund_profile: ["6_7", "5_7", "2_3", "NONE"],
            close_period_status: [
                "OPEN",
                "SUBSTANTIVE_REVIEW",
                "READY_TO_LOCK",
                "LOCKED",
            ],
            engagement_status: ["planned", "active", "completed", "archived"],
            fraud_plan_status: ["DRAFT", "READY_FOR_APPROVAL", "LOCKED"],
            je_control_rule: [
                "LATE_POSTING",
                "WEEKEND_USER",
                "ROUND_AMOUNT",
                "MANUAL_TO_SENSITIVE",
                "MISSING_ATTACHMENT",
            ],
            je_control_severity: ["LOW", "MEDIUM", "HIGH"],
            ledger_account_type: [
                "ASSET",
                "LIABILITY",
                "EQUITY",
                "REVENUE",
                "EXPENSE",
            ],
            org_role: ["admin", "manager", "staff", "client"],
            reconciliation_item_category: [
                "DIT",
                "OC",
                "UNAPPLIED_RECEIPT",
                "UNAPPLIED_PAYMENT",
                "TIMING",
                "ERROR",
                "OTHER",
            ],
            reconciliation_type: ["BANK", "AR", "AP", "GRNI", "PAYROLL", "OTHER"],
            response_status: ["PLANNED", "IN_PROGRESS", "COMPLETED", "CANCELLED"],
            response_type: [
                "CONTROL",
                "SUBSTANTIVE",
                "ANALYTICS",
                "SAMPLING",
                "OTHER",
            ],
            risk_rating: ["LOW", "MODERATE", "HIGH", "SIGNIFICANT"],
            risk_status: ["OPEN", "MONITORED", "CLOSED"],
            role_level: ["EMPLOYEE", "MANAGER", "SYSTEM_ADMIN"],
            severity_level: ["info", "warn", "error"],
            tax_account_type: ["MTA", "FIA", "IPA", "FTA", "UA"],
        },
    },
};
