#!/usr/bin/env bash
set -euo pipefail

TARGET_STATEMENTS=${TARGET_STATEMENTS:-44}
TARGET_BRANCHES=${TARGET_BRANCHES:-40}
TARGET_FUNCTIONS=${TARGET_FUNCTIONS:-44}
TARGET_LINES=${TARGET_LINES:-44}

VITEST_COVERAGE_STATEMENTS=$TARGET_STATEMENTS \
VITEST_COVERAGE_BRANCHES=$TARGET_BRANCHES \
VITEST_COVERAGE_FUNCTIONS=$TARGET_FUNCTIONS \
VITEST_COVERAGE_LINES=$TARGET_LINES \
  export VITEST_COVERAGE_STATEMENTS=$TARGET_STATEMENTS
export VITEST_COVERAGE_BRANCHES=$TARGET_BRANCHES
export VITEST_COVERAGE_FUNCTIONS=$TARGET_FUNCTIONS
export VITEST_COVERAGE_LINES=$TARGET_LINES

env_lines=$(grep -hv '^#' tests/config/*.env | tr -d '
')
while IFS= read -r line; do
  [ -z "$line" ] && continue
  export "$line"
done <<< "$env_lines"

npx vitest run --coverage
