#!/usr/bin/env bash
set -euo pipefail

TARGET_STATEMENTS=${TARGET_STATEMENTS:-45}
TARGET_BRANCHES=${TARGET_BRANCHES:-40}
TARGET_FUNCTIONS=${TARGET_FUNCTIONS:-45}
TARGET_LINES=${TARGET_LINES:-45}

VITEST_COVERAGE_STATEMENTS=$TARGET_STATEMENTS \
VITEST_COVERAGE_BRANCHES=$TARGET_BRANCHES \
VITEST_COVERAGE_FUNCTIONS=$TARGET_FUNCTIONS \
VITEST_COVERAGE_LINES=$TARGET_LINES \
  npm run coverage
