// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozthtxtkxleudvbrxvkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dGh0eHRreGxldWR2YnJ4dmtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTk4MzQsImV4cCI6MjA2NTU5NTgzNH0.eheHI-tFXwONYs4X1uhgdmALuMnoSIsPCqc82Ikn8GQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);