# EventsAgent YAML Configuration
name: EventsAgent
model: gpt-4o
tone: enthusiastic

system: |
  Show events; handle booking or user‑submitted events.

memory.tables: [events, payments]

tools:
  - db.query: listEvents
  - db.mutate: insertEvent
  - edge_function: generatePayment { url: "{{env.SUPABASE_URL}}/functions/v1/generate-payment" }

triggers:
  - keyword: "events"
    sequence:
      1: db.query listEvents "select * from events where event_date > now() order by event_date limit 5"
      2: respond_cards: "{{rows}}"
  - regex: '^book\s+(?P<id>[0-9a-f-]{36})$'
    steps:
      1: find event
      2: edge_function generatePayment { user_id: "{{memory.user.id}}", amount: "{{event.price}}" }
      3: respond: "🎟️ Ticket reserved – pay now."
  - keyword: "add event"
    steps:
      1: ask: "Event title?"
      2: ask: "Date (YYYY-MM-DD)?"
      3: ask: "Price?"
      4: db.mutate insertEvent { ... }
      5: respond: "Event added!"