-- ============================================================================
-- User Table Consolidation Plan (PHASE 4)
-- ============================================================================
-- Purpose: Consolidate user-related tables into single authoritative schema
-- Date: 2025-01-03
-- Risk Level: MEDIUM (requires data migration)
-- 
-- This migration consolidates:
--   - profiles, users, app_users → public.users
--   - members, memberships → public.memberships (with org_role)
--
-- IMPORTANT: This is a PLANNING/ANALYSIS migration. Actual data migration
-- should be done carefully with proper testing and backup procedures.
-- ============================================================================

-- ============================================================================
-- STEP 1: ANALYSIS AND VALIDATION
-- ============================================================================
-- Before proceeding, verify the current state:
--
-- 1. Check which tables exist:
--    SELECT tablename FROM pg_tables WHERE schemaname IN ('public', 'app')
--      AND tablename IN ('profiles', 'users', 'app_users', 'memberships', 'members');
--
-- 2. Check data counts:
--    SELECT 'profiles' as table_name, COUNT(*) FROM profiles
--    UNION ALL SELECT 'users', COUNT(*) FROM users
--    UNION ALL SELECT 'app_users', COUNT(*) FROM app_users
--    UNION ALL SELECT 'memberships', COUNT(*) FROM memberships
--    UNION ALL SELECT 'members', COUNT(*) FROM app.members;
--
-- 3. Check for conflicts (users with same email in multiple tables):
--    SELECT email, COUNT(*) FROM (
--      SELECT email FROM profiles WHERE email IS NOT NULL
--      UNION ALL SELECT email FROM users WHERE email IS NOT NULL
--      UNION ALL SELECT email FROM app_users WHERE email IS NOT NULL
--    ) t GROUP BY email HAVING COUNT(*) > 1;
--
-- 4. Check foreign key references:
--    SELECT 
--      tc.table_name, 
--      kcu.column_name,
--      ccu.table_name AS foreign_table_name,
--      ccu.column_name AS foreign_column_name
--    FROM information_schema.table_constraints AS tc
--    JOIN information_schema.key_column_usage AS kcu
--      ON tc.constraint_name = kcu.constraint_name
--    JOIN information_schema.constraint_column_usage AS ccu
--      ON ccu.constraint_name = tc.constraint_name
--    WHERE tc.constraint_type = 'FOREIGN KEY'
--      AND ccu.table_name IN ('profiles', 'users', 'app_users', 'memberships', 'members');
-- ============================================================================

-- ============================================================================
-- STEP 2: TARGET SCHEMA DEFINITION
-- ============================================================================
-- This section defines the target consolidated schema
-- DO NOT EXECUTE THIS MIGRATION DIRECTLY - it's for planning purposes
-- ============================================================================

-- Target: public.users (consolidated user table)
-- Columns from all user tables combined:
--   - id (UUID, PK, references auth.users)
--   - email (TEXT, UNIQUE, NOT NULL)
--   - name (TEXT) - from users table
--   - full_name (TEXT) - from profiles, app_users
--   - avatar_url (TEXT) - from profiles, users
--   - is_system_admin (BOOLEAN) - from users
--   - role (TEXT) - from profiles (deprecated, use memberships.role instead)
--   - metadata (JSONB) - from profiles
--   - created_at (TIMESTAMPTZ)
--   - updated_at (TIMESTAMPTZ)

-- Target: public.memberships (consolidated membership table)
-- Columns:
--   - id (UUID, PK)
--   - org_id (UUID, FK -> organizations)
--   - user_id (UUID, FK -> users)
--   - role (org_role ENUM) - unified role system
--   - created_at (TIMESTAMPTZ)
--   - updated_at (TIMESTAMPTZ)
--   - UNIQUE(org_id, user_id)

-- ============================================================================
-- STEP 3: MIGRATION STRATEGY (TO BE IMPLEMENTED)
-- ============================================================================
--
-- Phase 4A: Ensure target tables exist (use IF NOT EXISTS)
-- Phase 4B: Migrate data from source tables to target tables
-- Phase 4C: Update foreign key references
-- Phase 4D: Drop source tables (after verification)
--
-- Detailed implementation will be created based on analysis results.
-- ============================================================================

-- This is a planning/documentation migration - no executable SQL
-- Actual consolidation migration will be created after data analysis

SELECT 'User consolidation planning migration - see comments for strategy' AS status;

