-- Seed comprehensive action buttons for easyMO agent learning
INSERT INTO action_buttons (id, domain, label, payload, description) VALUES
-- Core Payment Domain (20+ buttons)
('pay-qr-gen-001', 'payments', 'Generate Payment QR', 'generate_payment_qr', 'Generate QR code for receiving payments'),
('pay-qr-scan-001', 'payments', 'Scan to Pay', 'scan_payment_qr', 'Scan QR code to make payment'),
('pay-momo-001', 'payments', 'Pay with MoMo', 'pay_with_momo', 'Make payment using Mobile Money'),
('pay-bill-001', 'payments', 'Pay Bills', 'pay_bills', 'Pay utility bills and services'),
('pay-status-001', 'payments', 'Check Payment Status', 'check_payment_status', 'Verify payment transaction status'),
('pay-request-001', 'payments', 'Request Payment', 'request_payment', 'Send payment request to someone'),
('pay-split-001', 'payments', 'Split Bill', 'split_bill', 'Split bill among multiple people'),
('pay-schedule-001', 'payments', 'Schedule Payment', 'schedule_payment', 'Set up recurring or future payments'),
('pay-refund-001', 'payments', 'Request Refund', 'request_refund', 'Request refund for transaction'),
('pay-balance-001', 'payments', 'Check Balance', 'check_balance', 'Check MoMo account balance'),
('pay-history-001', 'payments', 'Payment History', 'payment_history', 'View recent payment transactions'),
('pay-receipt-001', 'payments', 'Download Receipt', 'download_receipt', 'Get payment receipt'),
('pay-limits-001', 'payments', 'Check Limits', 'check_limits', 'View daily/monthly payment limits'),
('pay-airtime-001', 'payments', 'Buy Airtime', 'buy_airtime', 'Purchase mobile airtime'),
('pay-data-001', 'payments', 'Buy Data Bundle', 'buy_data', 'Purchase mobile data packages'),
('pay-tax-001', 'payments', 'Pay Taxes', 'pay_taxes', 'Pay government taxes and fees'),
('pay-insurance-001', 'payments', 'Pay Insurance', 'pay_insurance', 'Pay insurance premiums'),
('pay-school-001', 'payments', 'School Fees', 'pay_school_fees', 'Pay school fees and education costs'),
('pay-loan-001', 'payments', 'Loan Payment', 'pay_loan', 'Make loan repayment'),
('pay-savings-001', 'payments', 'Save Money', 'save_money', 'Transfer to savings account'),

-- Transport/Mobility Domain (25+ buttons)
('trans-driver-reg-001', 'transport', 'Register as Driver', 'register_driver', 'Sign up to become a driver'),
('trans-passenger-req-001', 'transport', 'Request Ride', 'request_ride', 'Request transportation'),
('trans-find-drivers-001', 'transport', 'Find Nearby Drivers', 'find_drivers', 'Search for available drivers'),
('trans-share-location-001', 'transport', 'Share Location', 'share_location', 'Share current GPS location'),
('trans-set-destination-001', 'transport', 'Set Destination', 'set_destination', 'Choose destination for trip'),
('trans-driver-online-001', 'transport', 'Go Online (Driver)', 'driver_go_online', 'Start accepting ride requests'),
('trans-driver-offline-001', 'transport', 'Go Offline (Driver)', 'driver_go_offline', 'Stop accepting requests'),
('trans-estimate-fare-001', 'transport', 'Estimate Fare', 'estimate_fare', 'Calculate trip cost estimate'),
('trans-book-driver-001', 'transport', 'Book This Driver', 'book_driver', 'Confirm booking with selected driver'),
('trans-cancel-trip-001', 'transport', 'Cancel Trip', 'cancel_trip', 'Cancel current trip request'),
('trans-trip-status-001', 'transport', 'Trip Status', 'trip_status', 'Check current trip status'),
('trans-rate-driver-001', 'transport', 'Rate Driver', 'rate_driver', 'Provide driver rating'),
('trans-rate-passenger-001', 'transport', 'Rate Passenger', 'rate_passenger', 'Provide passenger rating'),
('trans-emergency-001', 'transport', 'Emergency Help', 'emergency_help', 'Emergency assistance button'),
('trans-schedule-trip-001', 'transport', 'Schedule Trip', 'schedule_trip', 'Book trip for later'),
('trans-trip-history-001', 'transport', 'Trip History', 'trip_history', 'View past trips'),
('trans-driver-earnings-001', 'transport', 'Driver Earnings', 'driver_earnings', 'View earnings summary'),
('trans-vehicle-info-001', 'transport', 'Vehicle Info', 'vehicle_info', 'Update vehicle details'),
('trans-driver-documents-001', 'transport', 'Upload Documents', 'upload_documents', 'Upload driver licenses'),
('trans-passenger-safety-001', 'transport', 'Safety Features', 'safety_features', 'Access safety tools'),
('trans-route-options-001', 'transport', 'Route Options', 'route_options', 'Choose preferred route'),
('trans-payment-method-001', 'transport', 'Payment Method', 'payment_method', 'Select payment option'),
('trans-driver-support-001', 'transport', 'Driver Support', 'driver_support', 'Get help as driver'),
('trans-passenger-support-001', 'transport', 'Passenger Support', 'passenger_support', 'Get help as passenger'),
('trans-vehicle-maintenance-001', 'transport', 'Vehicle Maintenance', 'vehicle_maintenance', 'Schedule vehicle service'),

-- Commerce/Shopping Domain (20+ buttons)
('shop-browse-001', 'commerce', 'Browse Products', 'browse_products', 'View available products'),
('shop-search-001', 'commerce', 'Search Products', 'search_products', 'Search for specific items'),
('shop-add-cart-001', 'commerce', 'Add to Cart', 'add_to_cart', 'Add item to shopping cart'),
('shop-view-cart-001', 'commerce', 'View Cart', 'view_cart', 'See items in cart'),
('shop-checkout-001', 'commerce', 'Checkout', 'checkout', 'Proceed to payment'),
('shop-track-order-001', 'commerce', 'Track Order', 'track_order', 'Track delivery status'),
('shop-order-history-001', 'commerce', 'Order History', 'order_history', 'View past orders'),
('shop-categories-001', 'commerce', 'Product Categories', 'product_categories', 'Browse by category'),
('shop-pharmacy-001', 'commerce', 'Pharmacy', 'pharmacy', 'Medical and health products'),
('shop-hardware-001', 'commerce', 'Hardware Store', 'hardware', 'Construction and tools'),
('shop-groceries-001', 'commerce', 'Groceries', 'groceries', 'Food and household items'),
('shop-farmers-001', 'commerce', 'Local Farmers', 'farmers', 'Fresh produce from farmers'),
('shop-deals-001', 'commerce', 'Daily Deals', 'daily_deals', 'Special offers and discounts'),
('shop-wishlist-001', 'commerce', 'Wishlist', 'wishlist', 'Save items for later'),
('shop-compare-001', 'commerce', 'Compare Products', 'compare_products', 'Compare similar items'),
('shop-reviews-001', 'commerce', 'Product Reviews', 'product_reviews', 'Read customer reviews'),
('shop-vendor-contact-001', 'commerce', 'Contact Vendor', 'contact_vendor', 'Message the seller'),
('shop-bulk-order-001', 'commerce', 'Bulk Order', 'bulk_order', 'Order large quantities'),
('shop-prescription-001', 'commerce', 'Upload Prescription', 'upload_prescription', 'Upload medical prescription'),
('shop-delivery-options-001', 'commerce', 'Delivery Options', 'delivery_options', 'Choose delivery method'),

-- Business/Listings Domain (15+ buttons)
('biz-register-001', 'business', 'Register Business', 'register_business', 'List your business'),
('biz-profile-001', 'business', 'Business Profile', 'business_profile', 'Manage business information'),
('biz-discover-001', 'business', 'Discover Businesses', 'discover_businesses', 'Find local businesses'),
('biz-contact-001', 'business', 'Contact Business', 'contact_business', 'Get in touch with business'),
('biz-services-001', 'business', 'View Services', 'view_services', 'See available services'),
('biz-hours-001', 'business', 'Business Hours', 'business_hours', 'Check opening hours'),
('biz-location-001', 'business', 'Business Location', 'business_location', 'Get directions to business'),
('biz-reviews-business-001', 'business', 'Business Reviews', 'business_reviews', 'Read business reviews'),
('biz-rate-business-001', 'business', 'Rate Business', 'rate_business', 'Leave business rating'),
('biz-menu-001', 'business', 'View Menu', 'view_menu', 'See business menu/catalog'),
('biz-book-service-001', 'business', 'Book Service', 'book_service', 'Schedule appointment'),
('biz-business-hours-001', 'business', 'Update Hours', 'update_hours', 'Update business hours'),
('biz-inventory-001', 'business', 'Manage Inventory', 'manage_inventory', 'Update product inventory'),
('biz-promotions-001', 'business', 'Promotions', 'promotions', 'Create and manage promotions'),
('biz-analytics-001', 'business', 'Business Analytics', 'business_analytics', 'View business metrics'),

-- Events Domain (10+ buttons)
('event-discover-001', 'events', 'Discover Events', 'discover_events', 'Find events near you'),
('event-create-001', 'events', 'Create Event', 'create_event', 'Organize a new event'),
('event-rsvp-001', 'events', 'RSVP to Event', 'rsvp_event', 'Confirm event attendance'),
('event-details-001', 'events', 'Event Details', 'event_details', 'View event information'),
('event-share-001', 'events', 'Share Event', 'share_event', 'Share event with others'),
('event-tickets-001', 'events', 'Buy Tickets', 'buy_tickets', 'Purchase event tickets'),
('event-calendar-001', 'events', 'Add to Calendar', 'add_calendar', 'Save event to calendar'),
('event-location-001', 'events', 'Event Location', 'event_location', 'Get directions to event'),
('event-remind-001', 'events', 'Set Reminder', 'set_reminder', 'Get event reminder'),
('event-cancel-001', 'events', 'Cancel RSVP', 'cancel_rsvp', 'Cancel event attendance'),

-- Support/Help Domain (10+ buttons)
('help-faq-001', 'support', 'FAQ', 'faq', 'Frequently asked questions'),
('help-contact-001', 'support', 'Contact Support', 'contact_support', 'Get help from support team'),
('help-tutorials-001', 'support', 'Tutorials', 'tutorials', 'Learn how to use features'),
('help-report-issue-001', 'support', 'Report Issue', 'report_issue', 'Report a problem'),
('help-feedback-001', 'support', 'Send Feedback', 'send_feedback', 'Share your feedback'),
('help-account-001', 'support', 'Account Help', 'account_help', 'Help with account issues'),
('help-payment-support-001', 'support', 'Payment Support', 'payment_support', 'Help with payments'),
('help-technical-001', 'support', 'Technical Support', 'technical_support', 'Technical assistance'),
('help-escalate-001', 'support', 'Escalate Issue', 'escalate_issue', 'Escalate to human agent'),
('help-status-001', 'support', 'System Status', 'system_status', 'Check service status'),

-- User/Account Domain (8+ buttons)
('user-profile-001', 'user', 'My Profile', 'my_profile', 'View and edit profile'),
('user-settings-001', 'user', 'Settings', 'settings', 'Adjust app settings'),
('user-language-001', 'user', 'Change Language', 'change_language', 'Switch language preference'),
('user-notifications-001', 'user', 'Notifications', 'notifications', 'Manage notification settings'),
('user-privacy-001', 'user', 'Privacy Settings', 'privacy_settings', 'Control privacy options'),
('user-logout-001', 'user', 'Logout', 'logout', 'Sign out of account'),
('user-delete-001', 'user', 'Delete Account', 'delete_account', 'Delete user account'),
('user-referral-001', 'user', 'Refer Friends', 'refer_friends', 'Invite friends to easyMO')

ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label,
  payload = EXCLUDED.payload,
  description = EXCLUDED.description;