-- Add WhatsApp templates with correct structure
INSERT INTO whatsapp_templates (id, code, name_meta, category, domain, intent, language, body, footer, status, version, created_at, updated_at) VALUES
(gen_random_uuid(), 'welcome_message', 'Welcome Message', 'greeting', 'core', 'welcome', 'en', 'Welcome to easyMO! 🇷🇼 Your WhatsApp super-app for payments, transport, and shopping. How can I help you today?', 'Powered by easyMO', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'payment_qr_generated', 'Payment QR Generation', 'payments', 'payments', 'generate_qr', 'en', 'Here''s your payment QR code for {{amount}} RWF. Share this with anyone who needs to pay you, or they can scan it directly.', 'Scan to pay instantly', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'ride_request_confirmed', 'Ride Request Confirmation', 'transport', 'transport', 'request_ride', 'en', 'Your ride request from {{pickup}} to {{destination}} has been received. Finding drivers nearby...', 'We''ll connect you soon', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'driver_found', 'Driver Found', 'transport', 'transport', 'driver_match', 'en', 'Great news! {{driver_name}} is available for your trip. Vehicle: {{vehicle_details}}. Contact: {{phone}}', 'Tap to confirm booking', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'business_discovery', 'Business Discovery', 'business', 'business', 'discover_business', 'en', 'Found {{count}} {{business_type}} businesses near you: {{business_list}}. Which one would you like to know more about?', 'Discover local businesses', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'order_confirmed', 'Order Confirmation', 'commerce', 'commerce', 'order_confirm', 'en', 'Order confirmed! {{order_details}}. Total: {{total}} RWF. Estimated delivery: {{delivery_time}}', 'Track your order anytime', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'payment_success', 'Payment Success', 'payments', 'payments', 'payment_complete', 'en', 'Payment successful! {{amount}} RWF sent to {{recipient}}. Transaction ID: {{transaction_id}}', 'Keep this for your records', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'support_escalation', 'Support Escalation', 'support', 'support', 'escalate_human', 'en', 'I''ve escalated your issue to our support team. Reference: {{ticket_id}}. They''ll contact you within 30 minutes.', 'We''re here to help', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'event_reminder', 'Event Reminder', 'events', 'events', 'event_remind', 'en', 'Reminder: {{event_name}} starts in {{time_remaining}}. Location: {{location}}. See you there!', 'Don''t miss out', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'promo_offer', 'Promotional Offer', 'marketing', 'marketing', 'send_promo', 'en', 'Special offer! {{discount}}% off {{service_type}} today only. Use code: {{promo_code}}', 'Limited time offer', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'trip_completed', 'Trip Completed', 'transport', 'transport', 'trip_complete', 'en', 'Trip completed! Thanks for choosing easyMO. Please rate your experience with {{driver_name}}.', 'Safe travels always', 'APPROVED', 1, now(), now()),
(gen_random_uuid(), 'low_balance_alert', 'Low Balance Alert', 'payments', 'payments', 'balance_warning', 'en', 'Your MoMo balance is running low ({{balance}} RWF). Top up now to continue enjoying easyMO services.', 'Stay connected', 'APPROVED', 1, now(), now());