-- Catalog of authoritative web resources for Malta-focused agent learning.

CREATE TABLE IF NOT EXISTS public.web_knowledge_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  domain TEXT,
  jurisdiction TEXT[] DEFAULT '{}',
  tags TEXT[] DEFAULT '{}',
  priority INT DEFAULT 100,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.web_knowledge_sources ENABLE ROW LEVEL SECURITY;
-- Global read access via RLS helper (users already restricted at application layer).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'web_knowledge_sources' AND policyname = 'web_sources_read') THEN
    EXECUTE 'CREATE POLICY web_sources_read ON public.web_knowledge_sources FOR SELECT USING (true)';
  END IF;
END $$;
INSERT INTO public.web_knowledge_sources (title, url, domain, jurisdiction, tags, priority) VALUES
  ('MFSA Financial Reporting Guidelines', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','guidelines'], 10),
  ('Financial Reporting Manual for Licensed Entities in Malta', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','manual'], 10),
  ('IFRS Overview – IFRS Foundation', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','overview'], 5),
  ('IFRS Standard 1 – First-time Adoption of IFRS', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS1'], 5),
  ('IFRS Standard 2 – Share-based Payment', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS2'], 5),
  ('IFRS Standard 3 – Business Combinations', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS3'], 5),
  ('IFRS Standard 4 – Insurance Contracts', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS4'], 5),
  ('IFRS Standard 5 – Non-current Assets Held for Sale and Discontinued Operations', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS5'], 5),
  ('IFRS Standard 6 – Exploration for and Evaluation of Mineral Resources', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS6'], 5),
  ('IFRS Standard 7 – Financial Instruments: Disclosures', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS7'], 5),
  ('IFRS Standard 8 – Operating Segments', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS8'], 5),
  ('IFRS Standard 9 – Financial Instruments', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS9'], 5),
  ('IFRS Standard 10 – Consolidated Financial Statements', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS10'], 5),
  ('IFRS Standard 11 – Joint Arrangements', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS11'], 5),
  ('IFRS Standard 12 – Disclosure of Interests in Other Entities', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS12'], 5),
  ('IFRS Standard 13 – Fair Value Measurement', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS13'], 5),
  ('IFRS Standard 14 – Regulatory Deferral Accounts', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS14'], 5),
  ('IFRS Standard 15 – Revenue from Contracts with Customers', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS15'], 5),
  ('IFRS Standard 16 – Leases', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS16'], 5),
  ('IFRS Standard 17 – Insurance Contracts', 'https://www.ifrs.org/issued-standards/list-of-standards/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','IFRS17'], 5),
  ('Historical Annual Financial Reports of Malta-listed Companies', 'https://www.mse.com.mt/', 'financial_reporting', ARRAY['MT'], ARRAY['MSE','annual_reports'], 20),
  ('Annual Report of Bank of Valletta', 'https://www.bov.com/', 'financial_reporting', ARRAY['MT'], ARRAY['BOV','annual_report'], 20),
  ('Annual Report of HSBC Malta', 'https://www.hsbc.com.mt/', 'financial_reporting', ARRAY['MT'], ARRAY['HSBC','annual_report'], 20),
  ('Annual Report of APS Bank', 'https://www.apsbank.com/', 'financial_reporting', ARRAY['MT'], ARRAY['APS','annual_report'], 20),
  ('Auditor''s Report Guidelines in Malta', 'https://www.mia.org.mt/', 'audit', ARRAY['MT'], ARRAY['MIA','audit_guidelines'], 15),
  ('MFSA Regulatory Compliance Guidelines', 'https://www.mfsa.mt/regulatory/publications/', 'compliance', ARRAY['MT'], ARRAY['MFSA','compliance'], 10),
  ('Maltese GAAP Guidelines', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','GAAP'], 10),
  ('Consolidated Financial Reporting Guidelines in Malta', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','consolidation'], 10),
  ('Financial Reporting Standards for SMEs in Malta', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','SME'], 10),
  ('IFRS for SMEs', 'https://www.ifrs.org/issued-standards/ifrs-for-smes/', 'ifrs', ARRAY['INTL'], ARRAY['IFRS','SME'], 10),
  ('Malta Income Tax Act', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','tax_act'], 5),
  ('Malta Value Added Tax (VAT) Act', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','VAT'], 5),
  ('Malta Corporate Tax Guidelines', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','corporate_tax'], 5),
  ('Commissioner for Revenue Circulars – Overview', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','circulars'], 5),
  ('Malta Personal Tax Code', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','personal_tax'], 5),
  ('Malta Tax Regulations on Deductions', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','deductions'], 5),
  ('Malta Tax Regulations on Allowances', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','allowances'], 5),
  ('Malta Taxation of Dividends Guidelines', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','dividends'], 5),
  ('Malta Transfer Pricing Guidelines', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','transfer_pricing'], 5),
  ('Malta Tax Residency Regulations', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','residency'], 5),
  ('Malta Withholding Tax Regulations', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','withholding'], 5),
  ('VAT Registration and Compliance Guidelines in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','VAT_compliance'], 5),
  ('Tax Compliance Audit Reports in Malta', 'https://www.mfsa.mt/regulatory/publications/', 'audit', ARRAY['MT'], ARRAY['MFSA','tax_audit'], 15),
  ('Historical Tax Compliance Reports in Malta', 'https://www.mfsa.mt/regulatory/publications/', 'audit', ARRAY['MT'], ARRAY['MFSA','tax_reports'], 15),
  ('Circular on Tax Incentives for Malta', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','incentives'], 10),
  ('Circular on Tax Deductions and Credits', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','deductions_credits'], 10),
  ('Malta Customs and Excise Tax Regulations', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','customs'], 10),
  ('Documentation on Double Taxation Agreements for Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','dta'], 10),
  ('Malta Tax Authority Annual Report', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','annual_report'], 10),
  ('Guidelines on Electronic Filing of Tax Returns in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','efiling'], 10),
  ('Corporate Tax Filing Procedures in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','filing'], 10),
  ('Guidance on Tax Audits in Malta', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','tax_audit_guidance'], 10),
  ('Malta Taxpayer Rights and Obligations Document', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','rights_obligations'], 10),
  ('Guidelines on VAT Refunds in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','vat_refund'], 10),
  ('Circular on Changes to Maltese Tax Legislation', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','legislation_updates'], 10),
  ('Tax Regulations on Interest Income in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','interest_income'], 10),
  ('Tax Regulations on Rental Income in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','rental_income'], 10),
  ('Tax Regulations on Capital Gains in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','capital_gains'], 10),
  ('Tax Regulations on Employment Income in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','employment_income'], 10),
  ('Guidelines on Compliance with EU Tax Directives in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','eu_compliance'], 10),
  ('Malta Tax Appeals Process Documentation', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','appeals'], 10),
  ('Document on Tax Credits for Research and Development in Malta', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','rd_credits'], 10),
  ('Malta Tax Legislation on Digital Services', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','digital_services'], 10),
  ('Malta Environmental Taxes Guidelines', 'https://cfr.gov.mt/en/regulations/', 'tax', ARRAY['MT'], ARRAY['CFR','environmental_tax'], 10),
  ('Comprehensive Guide to Maltese Tax Law', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','comprehensive_guide'], 10),
  ('International Standards on Auditing (ISA) – Overview', 'https://www.ifac.org/publications-resources', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA'], 5),
  ('ISA 200 – Overall Objectives of the Independent Auditor', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA200'], 5),
  ('ISA 210 – Agreeing the Terms of Audit Engagements', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA210'], 5),
  ('ISA 220 – Quality Control for an Audit of Financial Statements', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA220'], 5),
  ('ISA 230 – Audit Documentation', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA230'], 5),
  ('ISA 240 – Auditor’s Responsibilities Relating to Fraud', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA240'], 5),
  ('ISA 250 – Consideration of Laws and Regulations in an Audit', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA250'], 5),
  ('ISA 260 – Communication with Those Charged with Governance', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA260'], 5),
  ('ISA 265 – Communicating Deficiencies in Internal Control', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA265'], 5),
  ('ISA 300 – Planning an Audit of Financial Statements', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA300'], 5),
  ('ISA 315 – Identifying and Assessing the Risks of Material Misstatement', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA315'], 5),
  ('ISA 320 – Materiality in Planning and Performing an Audit', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA320'], 5),
  ('ISA 330 – The Auditor’s Responses to Assessed Risks', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA330'], 5),
  ('ISA 402 – Audit Considerations for Service Organizations', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA402'], 5),
  ('ISA 450 – Evaluation of Misstatements Identified during the Audit', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA450'], 5),
  ('ISA 500 – Audit Evidence', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA500'], 5),
  ('ISA 505 – External Confirmations', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA505'], 5),
  ('ISA 510 – Initial Audit Engagements – Opening Balances', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA510'], 5),
  ('ISA 520 – Analytical Procedures', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA520'], 5),
  ('ISA 530 – Audit Sampling', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA530'], 5),
  ('ISA 540 – Auditing Accounting Estimates and Fair Value', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA540'], 5),
  ('ISA 550 – Related Parties', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA550'], 5),
  ('ISA 560 – Subsequent Events', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA560'], 5),
  ('ISA 570 – Going Concern', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA570'], 5),
  ('ISA 580 – Written Representations', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA580'], 5),
  ('ISA 600 – Audits of Group Financial Statements', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA600'], 5),
  ('ISA 610 – Using the Work of Internal Auditors', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA610'], 5),
  ('ISA 620 – Using the Work of an Auditor’s Expert', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA620'], 5),
  ('ISA 700 – Forming an Opinion and Reporting on Financial Statements', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA700'], 5),
  ('ISA 705 – Modifications to the Auditor’s Report', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA705'], 5),
  ('ISA 706 – Emphasis of Matter and Other Matter Paragraphs', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA706'], 5),
  ('ISA 710 – Comparative Information and Financial Statements', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA710'], 5),
  ('ISA 720 – Auditor’s Responsibilities Relating to Other Information', 'https://www.ifac.org/issued-standards', 'audit', ARRAY['INTL'], ARRAY['IFAC','ISA720'], 5),
  ('Local Audit Guidelines for Maltese Entities', 'https://www.mia.org.mt/', 'audit', ARRAY['MT'], ARRAY['MIA','local_guidelines'], 15),
  ('Internal Audit Manual for Maltese Entities', 'https://www.theiia.org/', 'audit', ARRAY['MT'], ARRAY['IIA','internal_audit'], 15),
  ('PwC Global Audit Manual Summary', 'https://www.pwc.com/gx/en/audit-services.html', 'audit', ARRAY['INTL'], ARRAY['PwC','methodology'], 20),
  ('Deloitte Audit Methodology Overview', 'https://www2.deloitte.com/global/en/services/audit.html', 'audit', ARRAY['INTL'], ARRAY['Deloitte','methodology'], 20),
  ('EY Global Audit Methodology Overview', 'https://www.ey.com/en_gl/audit', 'audit', ARRAY['INTL'], ARRAY['EY','methodology'], 20),
  ('KPMG Audit Approach Overview', 'https://home.kpmg/xx/en/home/services/audit.html', 'audit', ARRAY['INTL'], ARRAY['KPMG','methodology'], 20),
  ('Malta Institute of Accountants Audit Guidelines', 'https://www.mia.org.mt/', 'audit', ARRAY['MT'], ARRAY['MIA','audit_guides'], 15),
  ('Malta Companies Act (Cap. 386)', 'https://legislation.mt/eli/cap/386/eng', 'legal', ARRAY['MT'], ARRAY['legislation','companies_act'], 5),
  ('Malta Commercial Code', 'https://justice.gov.mt/', 'legal', ARRAY['MT'], ARRAY['legislation','commercial_code'], 20),
  ('Guidelines on the Preparation of Financial Statements under Maltese GAAP', 'https://www.mia.org.mt/', 'financial_reporting', ARRAY['MT'], ARRAY['MIA','gaap'], 10),
  ('Malta Institute of Accountants – Financial Reporting Publications', 'https://www.mia.org.mt/', 'financial_reporting', ARRAY['MT'], ARRAY['MIA','publications'], 10),
  ('Local Audit Standards for Maltese Entities', 'https://www.mia.org.mt/', 'audit', ARRAY['MT'], ARRAY['MIA','standards'], 10),
  ('MFSA Circular on Local GAAP and Financial Reporting', 'https://www.mfsa.mt/regulatory/circulars/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','local_gaap'], 10),
  ('Guidelines on the Application of the Companies Act in Malta', 'https://legislation.mt/eli/cap/386/eng', 'legal', ARRAY['MT'], ARRAY['legislation','companies_guidance'], 20),
  ('Malta Accounting, Auditing and Taxation Review', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','review'], 20),
  ('Malta Financial Reporting Review Board Guidelines', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','frb_guidelines'], 10),
  ('Guide to Corporate Governance for Maltese Companies', 'https://www.mfsa.mt/regulatory/publications/', 'governance', ARRAY['MT'], ARRAY['MFSA','corporate_governance'], 10),
  ('Malta Taxpayer’s Handbook', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','handbook'], 20),
  ('Malta Transfer Pricing Documentation Guidelines', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','transfer_pricing_doc'], 10),
  ('Guidelines on Internal Controls and Risk Management in Malta', 'https://www.mfsa.mt/regulatory/publications/', 'governance', ARRAY['MT'], ARRAY['MFSA','internal_controls'], 10),
  ('National Financial Reporting Standards for Malta', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','national_frs'], 10),
  ('MFSA Annual Regulatory Report', 'https://www.mfsa.mt/regulatory/publications/', 'compliance', ARRAY['MT'], ARRAY['MFSA','annual_report'], 10),
  ('Commissioner for Revenue – Taxpayer Guidance Documents', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','taxpayer_guidance'], 10),
  ('Malta Tax Legislation Updates', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','updates'], 10),
  ('Financial Reporting and Audit Practice in Malta – Research Papers', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','research'], 20),
  ('Malta Financial Reporting Conference Proceedings', 'https://www.mfsa.mt/regulatory/conferences/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','conference'], 20),
  ('Guide to IFRS Adoption in Malta', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','ifrs_adoption'], 10),
  ('Maltese Companies Financial Disclosure Guidelines', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','disclosure'], 10),
  ('Malta Tax Court Decisions and Interpretations', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','case_law'], 20),
  ('Local Tax Administration Guidelines', 'https://cfr.gov.mt/en/Pages/Publications.aspx', 'tax', ARRAY['MT'], ARRAY['CFR','admin_guidelines'], 20),
  ('Standards on Financial Performance Reporting in Malta', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','performance_reporting'], 10),
  ('Malta Auditing Standards and Ethics Guidelines', 'https://www.mia.org.mt/', 'audit', ARRAY['MT'], ARRAY['MIA','ethics'], 10),
  ('Audit Risk Assessment Guidelines for Maltese Entities', 'https://www.mia.org.mt/', 'audit', ARRAY['MT'], ARRAY['MIA','risk_assessment'], 10),
  ('Local GAAP Compliance Checklist for Maltese Companies', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','compliance_checklist'], 10),
  ('Annual Financial Disclosure Report Template for Malta', 'https://www.mfsa.mt/regulatory/publications/', 'financial_reporting', ARRAY['MT'], ARRAY['MFSA','disclosure_template'], 10);
