name: Setup pnpm environment
inputs:
  node-version:
    description: Node.js version to use
    required: true
  pnpm-version:
    description: pnpm version to install
    required: false
    default: '9'
  install:
    description: Run pnpm install after setup
    required: false
    default: 'true'
  cache-dependency-path:
    description: Dependency file(s) used for pnpm caching
    required: false
    default: pnpm-lock.yaml
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    - if: ${{ inputs.install == 'true' }}
      shell: bash
      run: pnpm install --frozen-lockfile
